Hw 5 chuck allocator
Margarita307/made-cpp-2020-hw pull request #7
Opened 2020-10-27 20:00 UTC by Margarita307

2020-10-31 14:58 UTC, SweetWeakness requested changes

2020-10-31 14:58 UTC, SweetWeakness commented on chuck_allocator/src/allocator.h
> +        Chunk* prev = nullptr;
нет, надо cоxранять указатель на следующий, а не на предыдущий. Подумайте почему!

2020-10-31 14:58 UTC, SweetWeakness commented on chuck_allocator/src/allocator.h
> +            new(p) T(args...);
std::forawrd

2020-11-02 18:10 UTC, Margarita307 commented on chuck_allocator/src/allocator.h
> +        Chunk* prev = nullptr;
Возможно, чем раньше был выделен участок памяти, тем больше вероятность, что он быстрее освободиться и нам, таким образом, придется меньше ходить по списку?

2020-11-04 02:03 UTC, merged